image: androidsdk/android-30
env:
script:
  - ./gradlew test assemble -PdisablePreDex
trigger:
  branch:
  - master
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback