kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - echo "hello world"
  - export

- name: slack
  commands:
  - docker run --rm \
    -e SLACK_WEBHOOK=https://hooks.slack.com/services/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 \
    -e PLUGIN_CHANNEL=#android \
    -e PLUGIN_USERNAME=DRONE CI \
    -e DRONE_REPO_OWNER=octocat \
    -e DRONE_REPO_NAME=hello-world \
    -e DRONE_COMMIT_SHA=7fd1a60b01f91b314f59955a4e4d4e80d8edf11d \
    -e DRONE_COMMIT_BRANCH=master \
    -e DRONE_COMMIT_AUTHOR=octocat \
    -e DRONE_COMMIT_AUTHOR_EMAIL=octocat@github.com \
    -e DRONE_COMMIT_AUTHOR_AVATAR="https://avatars0.githubusercontent.com/u/583231?s=460&v=4" \
    -e DRONE_COMMIT_AUTHOR_NAME="The Octocat" \
    -e DRONE_BUILD_NUMBER=1 \
    -e DRONE_BUILD_STATUS=success \
    -e DRONE_BUILD_LINK=http://github.com/octocat/hello-world \
    -e DRONE_TAG=1.0.0 \
    plugins/slack

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
