kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: test
  commands:
  - docker run --rm -w /tmp/src --platform linux/amd64 androidsdk/android-30 ./gradlew test

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
