kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - echo "hello world"

- name: slack
  slack-notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: #android
    username: Drone CI
    icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      
      {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
      
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

      Author: {{ build.author }}      

      Build: <{{ build.link }}| Drone Build {{ build.number }} ↗>
      
    when:
      status: [ success, failure ]
      branch: [ master ]

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
