kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - echo "hello world"

- name: slack
  secrets: [slack_webhook]
  commands:
  - docker run --rm -e SLACK_WEBHOOK=$slack_webhook -e PLUGIN_CHANNEL=#android -e DRONE_BUILD_STATUS=success plugins/slack

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
