kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
  commands:
  - ./gradlew test --debug --stacktrace

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
