kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - ./gradlew clean
  - ./gradlew test
- name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: android
      username: Drone CI
      icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
      link_names: true
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job. :+1:
        {{else}}
          build {{build.number}} failed. Fix me please. :sob: <@channel>
        {{/success}}

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
