kind: pipeline
type: docker
name: slack
steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    template: > 
      hello world

trigger:
  event:
    - push
