kind: pipeline
type: docker
name: default
image: androidsdk/android-30
script:
  - ./gradlew test assemble -PdisablePreDex
trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
