kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: test
  commands:
  - sh ./gradlew test

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
