kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - ./gradlew clean
  - ./gradlew test

- name: slack
  slack-notify:
    image: plugins/slack
    secrets: [slack_webhook]
    webhook: $slack_webhook     
    channel: your-channel-name
    template: >
      
      {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
      
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

      Author: {{ build.author }}      

      Build: <{{ build.link }}| Drone Build {{ build.number }} ↗>
      
    when:
      status: [ success, failure ]

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
