kind: pipeline
type: docker
name: default

steps:
- name: test
  image: androidsdk/android-30
  commands:
  - chmod +x ./gradlew && ./gradlew test

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
