kind: pipeline
type: docker
name: default

steps:
- name: test
  image: android30
  commands:
  - ./gradlew test

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
