kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build
  environment:
    ANDROID_SDK_ROOT : /Users/snapask-ci/Library/Android/sdk
    ANDROID_HOME : /Users/snapask-ci/Library/Android/sdk
    JAVA_HOME : /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
  commands:
  - echo "hello world"

- name: send
  image: plugins/webhook
  settings:
    urls:
      - https://hooks.slack.com/services/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
  content_type: application/json
  template: |
      payload={
        "channel": "#android", 
        "username": "webhookbot", 
        "text": "This is posted to #android and comes from a bot named webhookbot.", 
        "icon_emoji": ":ghost:"
      } 

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
